import { useState } from 'react';
import { asset, hardware, project, signals, taskGroups } from '../data/project';
import { Arrow, ResearchMedia, SectionLabel } from '../components/Primitives';

export function WhyRoom() {
  return <section id="why" className="section why wrap"><SectionLabel number="01">The research question</SectionLabel><div className="why-layout"><h2>There’s more<br />to an action<br />than <em>the task.</em></h2><div className="why-content"><p className="lead">A person points. Pauses. Begins to sit.<br />Changes their mind.</p><p>People coordinate through more than words. For a humanoid to collaborate, it must connect those signals to the right object, the right response, and the right moment.</p><p>ROOM pairs human nonverbal behavior with the robot actions it calls for—under task instructions that leave the target or response open.</p><div className="question-lines">{[['WHAT','Which object do you mean?'],['WHEN','Are you ready for me to act?'],['HOW','Should I change what I’m doing?']].map(([word,text]) => <div key={word}><span>{word}</span><p>{text}</p><Arrow /></div>)}</div><span className="source-note">RESEARCH MOTIVATION · §I / §III-B</span></div></div></section>;
}

export function Dataset() {
  const [selected, setSelected] = useState(0);
  const signal = signals[selected];
  return <section id="dataset" className="section dataset"><div className="wrap"><SectionLabel number="02">The ROOM dataset</SectionLabel><div className="section-heading"><h2>Human signals.<br /><em>Robot responses.</em></h2><p>One interaction. Both sides of the story.<br />A synchronized record of human behavior<br className="desktop-break" /> and humanoid manipulation.</p></div><div className="stats">{project.stats.map(stat => <div className="stat" key={stat.label}><div>{stat.value}<span>{stat.unit}</span></div><p>{stat.label}</p><span className="source-note">{stat.source}</span></div>)}</div><div className="signal-browser"><div className="signal-view"><img key={signal.image} src={asset(`assets/${signal.image}.webp`)} alt={signal.detail} width="700" height="540" loading="lazy" /><span className="view-tag">{signal.annotation}</span><span className="view-corner">{String(selected+1).padStart(2,'0')} / 05</span><div className="view-crosshair tl" aria-hidden="true" /><div className="view-crosshair br" aria-hidden="true" /></div><div className="signal-info"><div className="control-label">EXPLORE THE HUMAN SIGNAL</div><div className="signal-select" aria-label="Human signal views">{signals.map((item,i) => <button type="button" key={item.id} aria-pressed={i===selected} className={i===selected?'selected':''} onClick={() => setSelected(i)}>{item.label}<span>{String(i+1).padStart(2,'0')}</span></button>)}</div><div className="signal-copy" aria-live="polite"><h3>{signal.title}</h3><p>{signal.description}</p><span className="source-note">{signal.detail} · {signal.source}</span></div></div></div><div className="timeline"><div className="timeline-head"><h3>One shared clock.</h3><span>30 Hz <span className="muted">/ SYNCHRONIZED</span></span></div><div className="timeline-tracks" aria-label="Schematic of synchronized human and robot recording channels"><div className="time-ruler"><span>HUMAN ↔ HUMANOID</span><span>t</span><span>t + 1</span><span>t + 2</span></div>{[['HUMAN','Gaze · hands · body'],['VISION','Ego · head · chest RGB'],['ROBOT','State · action trajectories']].map(([label,description],i) => <div className="track" key={label}><span>{label}</span><div className={`track-line track-${i}`}><div /><span>{description}</span></div></div>)}<div className="sync-cursor" aria-hidden="true" /></div><div className="timeline-caption"><span>Aligned observations → corresponding robot actions</span><span>LeRobot format · §III-D · schematic</span></div></div></div></section>;
}

export function Tasks() {
  const [selected, setSelected] = useState(0);
  const task = taskGroups[selected];
  return <section id="tasks" className="section tasks wrap"><SectionLabel number="03">Interaction tasks</SectionLabel><div className="section-heading"><h2><em>40 ways</em><br />to read the room.</h2><p>Two grounding requirements.<br />Four interaction functions.<br />Tabletop and whole-body collaboration.</p></div><div className="taxonomy-family"><span>REFERENTIAL GROUNDING</span><span>INTERACTION-STATE GROUNDING</span></div><div className="taxonomy" aria-label="Interaction functions">{taskGroups.map((item,i) => <button type="button" key={item.id} aria-pressed={selected===i} className={selected===i?'selected':''} onClick={() => setSelected(i)}><span>0{i+1}</span><h3>{item.function}</h3><p>{item.question}</p><Arrow /></button>)}</div><div className="task-stage"><div className="task-media"><ResearchMedia key={task.id} name={task.video} poster={`assets/${task.image}.webp`} alt={`${task.name}: real experimental scene from the ROOM paper`} /><span className="media-label">{task.name}</span></div><div className="task-story" aria-live="polite"><span className="control-label">{task.family}</span><h3>{task.name}</h3><p>{task.description}</p><div className="cue-response"><span>HUMAN SIGNAL</span><strong>{task.cue}</strong><span>ROBOT RESPONSE</span><strong>{task.response}</strong></div><div className="sequence">{task.sequence.map((step,i) => <div key={step}><span>0{i+1}</span>{step}</div>)}</div><span className="source-note">Representative task group · {task.source}</span></div></div><p className="section-footnote">Tasks can require more than one grounding function. The examples above are the four evaluation task groups, rather than a complete list of all 40 tasks.</p></section>;
}

export function Collection() {
  const [selected, setSelected] = useState(0);
  const device = hardware[selected];
  return <section id="collection" className="section collection"><div className="wrap"><SectionLabel number="04">Behind the observations</SectionLabel><div className="section-heading"><h2>A room built<br />to <em>capture interaction.</em></h2><p>A human partner, a humanoid,<br />and a separate teleoperator.<br />Recorded together in a home environment.</p></div><div className="collection-layout"><figure className="collection-photo"><img src={asset('assets/setup.webp')} alt="ROOM collection setup with a Project Aria participant, Unitree G1, external motion capture cameras and a VR teleoperator" width="922" height="740" loading="lazy" /><figcaption>Collection setup · cropped from Fig. 2</figcaption></figure><div className="system-map"><div className="control-label">EXPLORE THE COLLECTION SYSTEM</div>{hardware.map((item,i) => <button key={item.id} type="button" aria-pressed={selected===i} className={selected===i?'selected':''} onMouseEnter={() => setSelected(i)} onFocus={() => setSelected(i)} onClick={() => setSelected(i)}><span>{item.owner}</span><strong>{item.name}</strong><Arrow /></button>)}<div className="device-output" aria-live="polite"><span className="control-label">{device.name} → RECORDED SIGNALS</span><div>{device.outputs.map(output => <span key={output}>{output}</span>)}</div><p>{device.description}</p><span className="source-note">{device.source}</span></div></div></div><div className="collection-note"><span>TRAINING → RICH MULTIMODAL RECORDINGS</span><Arrow /><span>INFERENCE → ONBOARD OBSERVATIONS</span><p>The semantic behavior classifier is trained with supervision from the external motion-capture system; inference uses skeletons from the robot’s head and chest cameras. <span>§IV-B</span></p></div></div></section>;
}
